# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Deliveroo
email: root@deliverooco.uk
description: > # this means to ignore newlines until "baseurl:"
  Deliveroo's coding guidelines
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://deliveroo.engineering" # the base hostname & protocol for your site

repository: "deliveroo/guidelines"
  
# Build settings
markdown: kramdown

# Plugins
gems:
   - jekyll-mentions
   - jemoji
   - jekyll-redirect-from
   - jekyll-sitemap
   - jekyll-feed

collections:
  guidelines:
    output:       true
    permalink:    /guide/:path/

defaults:
  - scope:
      path:       ""
      type:       guidelines
    values:
      layout:     guidelines

exclude:
  - archive
  - Gemfile
  - Gemfile.lock
  - Guardfile
  - token
  - bin
